# Generated by Django 6.0.5 on 2026-05-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ImageField(blank=True, null=True, upload_to='captures/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.categorie')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['-datecreation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datecreation', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='activities.journal')),
            ],
            options={
                'verbose_name': "Historique d'activité",
                'verbose_name_plural': "Historiques d'activités",
                'ordering': ['-datecreation'],
            },
        ),
    ]
