# Generated by Django 6.0.5 on 2026-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
