# Generated by Django 6.0.5 on 2026-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_categorie_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('resolu', 'Résolu')], default='brouillon', max_length=20),
        ),
    ]
