# Generated by Django 6.0.5 on 2026-05-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_journal_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueactivite',
            name='deleted_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueactivite',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='activities.journal'),
        ),
    ]
