# Generated by Django 6.0.5 on 2026-05-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_historiqueactivite_deleted_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueactivite',
            options={},
        ),
        migrations.AlterField(
            model_name='historiqueactivite',
            name='datecreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historiqueactivite',
            name='deleted_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueactivite',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.journal'),
        ),
    ]
